FROM node:23-alpine 

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

EXPOSE 3000

ENV REACT_APP_BACKED_API="http://localhost:5000/api"
ENV REACT_APP_GOOGLE_CLIENT_ID="581830351494-9dogtcht1tgct16lfulhb6rigqgp8q4q.apps.googleusercontent.com"
ENV PORT=3000   

RUN npm install -g serve

CMD ["serve", "-s", "build"]