apiVersion: v1 
kind: Pod
metadata:
  name: fit-factory-client
  labels:
    name: fit_factory_client
    app: frontend
spec:
  containers:
    - name: fit-factory-client
      image: fit_factory_client:latest
      env:
        - name: REACT_APP_BACKED_API
          value: http://backend-clustserip:5000/api
