apiVersion: v1 
kind: Pod
metadata:
  name: fit-factory-client
  labels:
    name: fit-factory-client
    app: frontend
spec:
  containers:
    - name: fit-factory-client
      image: fit_factory_client:2.0
