apiVersion: v1 
kind: Service
metadata:
  name: fit-factory-client-nodeport
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000  
  selector:
    name: fit_factory_client
    app: frontend
  