apiVersion: apps/v1
kind: Deployment
metadata:
  name: fit-factory-server-deployment-2
  labels:
    name: fit-factory-server-deployment
spec:
  selector:
    matchLabels:
      name: fit-factory-server-deployment-pod
  template:
    metadata:
      name: fit-factory-server-deployment-pod
      labels:
        name: fit-factory-server-deployment-pod
    spec:
      containers:
        - name: fit-factory-server-container
          image: fit_factory_server:2.0   
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
    
  
    