apiVersion: v1
kind: Service
metadata:
  name: fit-factory-server-nodeport
  labels:
    name: fit-factory-server-nodeport
spec:
  type: NodePort
  selector:
      name: fit-factory-server
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30008
