apiVersion: v1
kind: Service
metadata:
  name: fit-factory-nodeport
  labels:
    name: fit-factory-nodeport
spec:
  type: NodePort
  selector:
      app: fitfactory-server
      type: backend
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30008
