apiVersion: v1
kind: Service
metadata:
  name: fit-factory-server-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: backend
    name: fit-factory-server
  ports:
  - port: 5000
    targetPort: 5000
